// Auto-generated by scripts/generate-module-index.js
// Do not edit manually

// ATENÇÃO: Este arquivo não pode importar de fora do diretorio frontend/
// Next.js bloqueia imports de ../../../../modules/
// Use o sistema de registry.ts com imports dinâmicos ao invés deste arquivo

// import { ModuleRoutes as Routes_sistema } from '../../../../modules/sistema/frontend/routes';

export const AllModuleRoutes: unknown[] = [
  // Rotas de módulos instalados aparecerão aqui
  // DEPRECATED: Use /modules/[module]/[...slug] com registry.ts
];
