// Auto-generated by scripts/generate-module-index.js
// Do not edit manually

import { ModuleRoutes as Routes_module_exemplo } from '../../../../modules/module-exemplo/frontend/routes';

export const AllModuleRoutes = [
  ...Routes_module_exemplo,
];
