// Auto-generated by scripts/generate-module-index.js
// Do not edit manually

// Importações de rotas de módulos serão adicionadas dinamicamente
// quando módulos forem instalados via sistema de upload

export const AllModuleRoutes: any[] = [
  // Rotas de módulos instalados aparecerão aqui
];
